# -*- coding: utf-8 -*-
"""superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAb-ZHB9FzK66ydeKIGJT0UCkSFLOdNW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split
from scipy import stats

import pandas as pd
path = "/content/drive/MyDrive/SampleSuperstore_data.csv"
df = pd.read_csv(path)

print(df.head())

print(df.info())

print(df.isnull().sum())

print("Average Sales:", np.mean(df["Sales"]))

sales = df.groupby("Category")["Sales"].sum()
print(sales)

plt.figure(figsize=(6,4))
plt.bar(sales.index, sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["Sales"], bins=30, edgecolor="black")
plt.title("Sales Distribution")
plt.xlabel("Sales")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(data=df, x="Sales", y="Profit")
plt.title("Sales vs Profit")
plt.show()

X_train, X_test = train_test_split(df, test_size=0.2, random_state=42)

print("Training Rows:", len(X_train))
print("Testing Rows:", len(X_test))

print("Mean Sales:", stats.tmean(df["Sales"]))

plt.figure(figsize=(10, 5))
sns.histplot(df['Profit'], bins=30, kde=True)
plt.title('Distribution of Profit')
plt.xlabel('Profit')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x=df['Profit'])
plt.title('Box Plot of Profit')
plt.xlabel('Profit')
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(df['Sales'], bins=30, kde=True)
plt.title('Distribution of Sales')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x=df['Sales'])
plt.title('Box Plot of Sales')
plt.xlabel('Sales')
plt.show()

plt.figure(figsize=(12, 6))
sns.scatterplot(x='Discount', y='Profit', data=df, hue='Profit', palette='viridis')
plt.axhline(y=0, color='r', linestyle='--', label='Zero Profit Line') # Add a line for zero profit
plt.title('Discount vs. Profit')
plt.xlabel('Discount')
plt.ylabel('Profit')
plt.legend()
plt.show()

# Create discount bins
df['Discount_Bin'] = pd.cut(df['Discount'], bins=np.arange(0, 1.1, 0.1), right=False)

# Calculate average profit per discount bin
profit_by_discount_bin = df.groupby('Discount_Bin')['Profit'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(x='Discount_Bin', y='Profit', data=profit_by_discount_bin, palette='coolwarm')
plt.axhline(y=0, color='r', linestyle='--', label='Zero Profit Line')
plt.title('Average Profit by Discount Bin')
plt.xlabel('Discount Range')
plt.ylabel('Average Profit')
plt.xticks(rotation=45)
plt.legend()
plt.show()

numerical_df = df.select_dtypes(include=[np.number])
correlation_matrix = numerical_df.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Heatmap of Numerical Attributes')
plt.show()

